Create a mongoose schema for user
abeg-help/backend pull request #52
Opened 2023-10-18 23:52 UTC by Chimise

# Pull Request Template

## Description

Create a mongoose schema for a user with necessary fields and helper methods for verifying passwords and generating JWT tokens.

## Related Issue

- Fixes #49

## Contribution Guidelines

Before submitting this pull request, please review our [Contribution Guidelines](https://github.com/abeg-help/backend/blob/dev/CONTRIBUTING.md) to understand how to contribute to this project.

## Checklist

- [x] I have reviewed the Contribution Guidelines linked above.
- [x] I have tested my changes thoroughly and ensured that all existing tests pass.
- [x] I have provided clear and concise commit messages.
- [x] I have updated the project's documentation as necessary.

## Screenshots (if applicable)

## Additional context (if needed)
Installed Dependencies
- Bcryptjs - For hashing user password

2023-10-18 23:53 UTC, Chimise commented
@Klin-Coders @Toyin5 @JC-Coder , please kindly review this PR

2023-10-19 06:12 UTC, Toyin5 commented on src/models/User.ts
Just a suggestion.
Instead of isProfileComplete, why just a verified field?
Sound more readable

2023-10-19 06:15 UTC, Toyin5 commented on src/models/User.ts
I thought all tokens will be stored on the redis cache
So we don't need a field for it here

2023-10-19 06:18 UTC, Chimise commented on src/models/User.ts
isProfileComplete is more specific that the user has completed his profile, verified can mean many things - That the user verified the email address or that the user confirmed the phone number.

2023-10-19 06:21 UTC, Chimise commented on src/models/User.ts
Just remember I forgot to add the isEmailVerified flag to show whether a user email is verified.

2023-10-19 06:26 UTC, Toyin5 commented on src/models/User.ts
Oh! That's what i thought you were doing.
If so, they should be a method to change the flag to true onSave(). Isn't it?

2023-10-19 06:28 UTC, Chimise commented on src/models/User.ts
It depends, if the refresh token is short lived like 12 hours which is not always the case, we can store them only in Redis. But if it is going to stay up to a month or more, we need to store it in a database. Remember Redis is a temporal storage, you can lose data. It does not store on disk, you will have to do that manually.

2023-10-19 06:31 UTC, Toyin5 approved these changes
Seems fine

2023-10-19 06:33 UTC, Toyin5 commented on src/models/User.ts
Thanks for clearing that!

2023-10-19 06:41 UTC, Chimise commented
Don't merge yet, forgot to add a flag to know that the user email is verified. I might also need to store add a field to store the token or we can use a jwt token for that without needing to store it on the db

2023-10-19 08:22 UTC, Klin-Coders requested changes

2023-10-19 08:22 UTC, Klin-Coders commented on src/models/User.ts
I have some issues that needs clarifications

1. why did you make most of the interface optional, i reckon they should all be required and if we wanna generate sub types from the main interface we can use the ts Pick or Omit to extract what is needed

2023-10-19 08:22 UTC, Klin-Coders commented on src/models/User.ts
I would also like to address the inconsistency in schema object format 

its best to maintain all as this format 
```
email: {
      type: String,
      required: [true, 'Email is a required field'],
    },
```
instead of having some as above and some like this 

```
phoneNo: String,
```

2023-10-19 08:22 UTC, Klin-Coders commented on src/models/User.ts
i would also like to advise that the naming of `phoneNo` to become `phoneNumber` or `mobile` or create an array for numbers object , primary and secondary if need be, no need to shorten and have less descriptive names

2023-10-19 08:22 UTC, Klin-Coders commented on src/models/User.ts
i think the following fields would be needed in the user schema and we can add more as we progress

```
ipAddress
lastLogin
loginRetries
address - an array containing a sub schema or separate schema
location
gender
idType  - enum containing bvn, intl passport, nin, etc
isIdVerified
isSuspended
isDeleted
```

and more as we progress

2023-10-19 08:22 UTC, Klin-Coders commented on src/models/User.ts
also we should add unique flags to a couple of fields that we do not want duplicate entries for eg `email` and `mobile`

2023-10-19 08:22 UTC, Klin-Coders commented on src/models/User.ts
i would like to ask if the idea is to support simultaneous logins. if not then we should probably not store the only refresh token s an array

2023-10-19 08:22 UTC, Klin-Coders commented on src/models/User.ts
We need to stop a couple of fields from being selected in the first place rather than deleting it from the stringified object which can be costly 

```
password: {
  type:  String,
  required:  [true, 'Password is a required field'],
  select: false
}
```

this way ensures this field is never selected or sent back, unless w=we manually select it from the db

2023-10-19 08:26 UTC, Klin-Coders commented on src/models/User.ts
We would also need to index some fields based on read & write ratio to speed up lookups

i reckon we should have indexes on  
`email, mobile` at least for now

2023-10-19 08:34 UTC, Chimise commented on src/models/User.ts
For making some properties optional, I make it requires initially but this can introduce bugs into our application. If a user signs up with Google OAuth or single sign in, the password can be undefined and trying to hash it on save will throw error.

2023-10-19 08:37 UTC, Chimise commented on src/models/User.ts
I will update that the inconsistency in the schema, I used an object only when there are additional properties to add apart from the data type.

2023-10-19 08:43 UTC, Klin-Coders commented on src/models/User.ts
> For making some properties optional, I make it requires initially but this can introduce bugs into our application. If a user signs up with Google OAuth or single sign in, the password can be undefined and trying to hash it on save will throw error.

there is already a check you added which stops the password from being hashed unless it was modified
`  if (this.password && this.isModified('password')) { ... `

also it enforces better types if we try and limit optional fields, if a subset of the tpes are needed, anyone can extend the main types and pick or omit what they need

2023-10-19 08:45 UTC, Chimise commented on src/models/User.ts
I will add those additional properties suggested. we will be using multiple authentication mechanisms right, if we make the email unique, we will need to bind all authentication methods to the same user. That means if a user previously signed in with email and password and later attempt to sign in with say google auth with the same email, we cannot create a new account for the user as that will throw an error, we will have to link the Google account to the previously created user.

2023-10-19 08:48 UTC, Klin-Coders commented on src/models/User.ts
> I will add those additional properties suggested. we will be using multiple authentication mechanisms right, if we make the email unique, we will need to bind all authentication methods to the same user. That means if a user previously signed in with email and password and later attempt to sign in with say google auth with the same email, we cannot create a new account for the user as that will throw an error, we will have to link the Google account to the previously created user.

i suppose so, do you have other ideas, i think we should enforce users being able to have one account regardless of the sign inmethod, so far the email i the same, we cannot be looking up an email and have it return 2 different uers> Huge issue

2023-10-19 08:52 UTC, Chimise commented on src/models/User.ts
For the refreshTokens field, I taught about adding any created refresh token to this array and removing it on logout. We cannot store that only on Redis except if it is going to be short lived. We can decide to say logout all active logins when a user changes a password. If there other important fields to add we can talk about that.

2023-10-19 08:55 UTC, Chimise commented on src/models/User.ts
I have already added to a toJSON method to delete private fields like password before sending to the client

2023-10-19 08:55 UTC, Klin-Coders commented on src/models/User.ts
> For the refreshTokens field, I taught about adding any created refresh token to this array and removing it on logout. We cannot store that only on Redis except if it is going to be short lived. We can decide to say logout all active logins when a user changes a password. If there other important fields to add we can talk about that.

Great thought.
i was thinking about how arrays are difficult to work with in mongodb and require extra overhead or removing and adding data 

also my suggestion is that for a platform this sensitive, we should not allow simultaneous logins, so people do not leave their accounts with funds littered on multiple devices, bet to save the `refreshToken` as a string in the db and remove it on logout, also same in redis

2023-10-19 09:18 UTC, Ryan-Zayne commented on src/models/User.ts
> Great thought. i was thinking about how arrays are difficult to work with in mongodb and require extra overhead or removing and adding data
> 

Now I see why you were initially against multi device login support.

Each operation we make will require the stress of thinking about how to modify the array accordingly, leading to more unavoidable boilerplate code
The

2023-10-19 09:22 UTC, Ryan-Zayne commented on src/models/User.ts
> also my suggestion is that for a platform this sensitive, we should not allow simultaneous logins, so people do not leave their accounts with funds littered on multiple devices, bet to save the `refreshToken` as a string in the db and remove it on logout, also same in redis
>

Although still on this, should we as well be removing the token when token reuse is detected? Or is that already a given?

2023-10-19 18:26 UTC, Chimise commented
@Klin-Coders, @Ryan-Zayne I updated the PR with the requested changes. Please kindly review.

2023-10-19 18:49 UTC, Ryan-Zayne commented
Looks good so far
But it seems you and @Klin-Coders later to leave the toJSON as is yeah?

2023-10-19 21:15 UTC, Klin-Coders approved these changes
LGTM: although i till have strong reservations for looping through an array on each db call

but will approve

2023-10-19 21:16 UTC, merged